language: r

cache: packages
warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev


## do not build vignettes or manual
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings" 
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


branches:
  only:
    - master
    - release


r_packages:
  - rgl

# r_binary_packages:
#   - rgl


# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "f1fa2317-1459-445c-a21b-a28179363004")'
