language: r

cache: packages
warnings_are_errors: false

r_binary_packages:
  - rgl  
  
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev

branches:
  only:
    - master
    - release

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "f1fa2317-1459-445c-a21b-a28179363004")'
